version: "3.3"
services:

  proxy:
    container_name: ${STACK_NAME?Variable not set}-traefik
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"
    networks:
      - traefik-public
      - default
    volumes:
      - "../development/letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker=true
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
      # Enable the Dashboard and API in insecure mode for local development
      #- --api.insecure=true
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=apps@interlink-project.eu"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

  frontend:
    image: "interlinkproject/frontend:latest"
    environment:
      - REACT_APP_BASE_URI=http://dev.interlink-project.eu
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=${PORT}
      - "traefik.http.routers.${STACK_NAME?Variable not set}-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-frontend.tls=true"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-frontend.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"

  coproduction:
    image: interlinkproject/backend-coproduction:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-coproduction.loadbalancer.server.port=${PORT}
      - "traefik.http.routers.${STACK_NAME?Variable not set}-coproduction.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-coproduction.tls=true"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-coproduction.rule=Host(`${DOMAIN}`) && PathPrefix(`/coproduction`)"
      - traefik.http.routers.${STACK_NAME?Variable not set}-coproduction.middlewares=coproduction-stripprefix
      - traefik.http.middlewares.coproduction-stripprefix.stripprefix.prefixes=/coproduction

  catalogue:
    image: interlinkproject/backend-catalogue:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-catalogue.loadbalancer.server.port=${PORT}
      - "traefik.http.routers.${STACK_NAME?Variable not set}-catalogue.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-catalogue.tls=true"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-catalogue.rule=Host(`${DOMAIN}`) && PathPrefix(`/catalogue`)"
      - traefik.http.routers.${STACK_NAME?Variable not set}-catalogue.middlewares=catalogue-stripprefix
      - traefik.http.middlewares.catalogue-stripprefix.stripprefix.prefixes=/catalogue

  auth:
    image: interlinkproject/backend-auth:latest
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}/auth
      - PORT=${PORT}
      - BASE_PATH=/auth
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?retryWrites=true&w=majority
      - DATABASE_NAME=data
      - COLLECTION_NAME=acl_resources
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-auth.loadbalancer.server.port=${PORT}
      - "traefik.http.routers.${STACK_NAME?Variable not set}-auth.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-auth.tls=true"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-auth.rule=Host(`${DOMAIN}`) && PathPrefix(`/auth`)"

  acl:
    image: interlinkproject/backend-acl:latest
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}/acl
      - PORT=${PORT}
      - BASE_PATH=/acl
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?retryWrites=true&w=majorit
      - DATABASE_NAME=data
      - COLLECTION_NAME=users
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-acl.loadbalancer.server.port=${PORT}
      - "traefik.http.routers.${STACK_NAME?Variable not set}-acl.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-acl.tls=true"
      - "traefik.http.routers.${STACK_NAME?Variable not set}-acl.rule=Host(`${DOMAIN}`) && PathPrefix(`/acl`)"
      - traefik.http.routers.${STACK_NAME?Variable not set}-acl.middlewares=acl-stripprefix
      - traefik.http.middlewares.acl-stripprefix.stripprefix.prefixes=/acl