name: build-and-publish-docker-postgres

on:
  push:
    branches:
      - "basic_deployment"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/postgres
          push: true
          tags: interlinkproject/postgres:latest
          cache-from: type=registry,ref=interlinkproject/postgres:buildcache
          cache-to: type=registry,ref=interlinkproject/postgres:buildcache,mode=max
